#!/bin/bash
# MR-Krabs Vault Setup Script
#
# This script initializes the encrypted vault for storing LLM provider API keys.
# 
# SECURITY WARNING: The master key generated by this script is CRITICAL.
# If lost, the vault cannot be decrypted. Store it securely and NEVER share.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Default paths (can be overridden by environment)
VAULT_PATH="${MRKRABS_VAULT_PATH:-/etc/mrkrabs/vault.enc}"
MASTER_KEY_FILE="${MRKRABS_MASTER_KEY_FILE:-$HOME/.mrkrabs/master.key}"
KEYRING_SERVICE="mrkrabs-llm-vault"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=========================================="
echo "  MR-Krabs Vault Setup"
echo "=========================================="
echo ""

# Function to display help
show_help() {
    echo "Usage: $0 [command]"
    echo ""
    echo "Commands:"
    echo "  init        Initialize new vault with random master key"
    echo "  add-key     Add LLM provider API keys to the vault"
    echo "  list        List providers in the vault"
    echo "  status      Show vault status and configuration"
    echo ""
    echo "Environment Variables:"
    echo "  MRKRABS_VAULT_PATH     Path to encrypted vault file (default: /etc/mrkrabs/vault.enc)"
    echo "  MRKRABS_MASTER_KEY_FILE  Path to master key file (default: ~/.mrkrabs/master.key)"
    echo "  VAULT_MASTER_KEY       Master encryption key (alternative to file)"
    echo ""
    echo "Examples:"
    echo "  $0 init"
    echo "  $0 add-key openai sk-123..."
    echo "  $0 list"
    echo ""
}

# Initialize new vault
init_vault() {
    echo -e "${YELLOW}Initializing new encrypted vault...${NC}"
    echo ""
    
    # Create directories
    mkdir -p "$(dirname "$VAULT_PATH")"
    mkdir -p "$(dirname "$MASTER_KEY_FILE")"
    
    # Check if vault already exists
    if [ -f "$VAULT_PATH" ]; then
        echo -e "${RED}✗ Vault already exists at $VAULT_PATH${NC}"
        echo "  Remove it first or use a different path:"
        echo "    rm $VAULT_PATH"
        exit 1
    fi
    
    # Generate master key using Python (for proper Fernet key generation)
    MASTER_KEY=$(python3 -c "
from cryptography.fernet import Fernet
import sys

key = Fernet.generate_key().decode()
sys.stdout.write(key)
")
    
    if [ -z "$MASTER_KEY" ]; then
        echo -e "${RED}✗ Failed to generate master key${NC}"
        exit 1
    fi
    
    # Save master key to file with restrictive permissions
    echo "$MASTER_KEY" > "$MASTER_KEY_FILE"
    chmod 600 "$MASTER_KEY_FILE"
    
    # Initialize the vault using Python
    python3 -c "
import os
os.environ['VAULT_MASTER_KEY'] = '$MASTER_KEY'

from src.core.vault import initialize_vault

print(f'\u2713 Vault created at: $VAULT_PATH')
" || {
        echo -e "${RED}✗ Failed to initialize vault${NC}"
        rm -f "$MASTER_KEY_FILE"
        exit 1
    }
    
    echo ""
    echo -e "${GREEN}✓ Vault initialized successfully!${NC}"
    echo ""
    echo -e "${RED}🔴 CRITICAL SECURITY NOTICE 🔴${NC}"
    echo ""
    echo "Master key saved to: $MASTER_KEY_FILE"
    echo ""
    echo "IMPORTANT:"
    echo "  1. NEVER commit the master key to version control"
    echo "  2. Back it up securely (password manager, encrypted storage)"
    echo "  3. If lost, the vault CANNOT be recovered"
    echo ""
    echo "Next steps:"
    echo "  $0 add-key openai <your-openai-api-key>"
    echo "  $0 add-key anthropic <your-anthropic-api-key>"
    echo ""
}

# Add provider API key to vault
add_key() {
    if [ $# -lt 2 ]; then
        echo -e "${RED}✗ Usage: $0 add-key <provider> <api_key>${NC}"
        echo ""
        echo "Providers:"
        echo "  openai     - OpenAI API key (starts with sk-)"
        echo "  anthropic  - Anthropic API key (starts with anthro-)"
        echo "  openrouter - OpenRouter API key"
        echo ""
        exit 1
    fi
    
    PROVIDER="$1"
    API_KEY="$2"
    
    echo -e "${YELLOW}Adding API key for provider: $PROVIDER${NC}"
    echo ""
    
    # Validate provider name
    case "$PROVIDER" in
        openai|anthropic|openrouter)
            ;;
        *)
            echo -e "${RED}✗ Unknown provider: $PROVIDER${NC}"
            echo "  Valid providers: openai, anthropic, openrouter"
            exit 1
            ;;
    esac
    
    # Validate API key format (basic check)
    if [ ${#API_KEY} -lt 10 ]; then
        echo -e "${RED}✗ API key appears too short (must be at least 10 characters)${NC}"
        exit 1
    fi
    
    # Check vault exists
    if [ ! -f "$VAULT_PATH" ]; then
        echo -e "${RED}✗ Vault not found at $VAULT_PATH${NC}"
        echo "  Run '$0 init' first to create the vault"
        exit 1
    fi
    
    # Load master key from environment or file
    if [ -z "$VAULT_MASTER_KEY" ]; then
        if [ -f "$MASTER_KEY_FILE" ]; then
            export VAULT_MASTER_KEY=$(cat "$MASTER_KEY_FILE")
        else
            echo -e "${RED}✗ Master key not found${NC}"
            echo "  Set VAULT_MASTER_KEY environment variable or use $MASTER_KEY_FILE"
            exit 1
        fi
    fi
    
    # Add key to vault using Python (hides key from shell history)
    python3 -c "
import os
from src.core.vault import Vault

vault = Vault.create(
    backend='encrypted',
    vault_path='$VAULT_PATH',
    master_key=os.environ['VAULT_MASTER_KEY']
)

try:
    vault.add_provider_key('$PROVIDER', '$API_KEY')
    print(f'\u2713 API key added for provider: $PROVIDER')
except Exception as e:
    print(f'\u2717 Failed to add key: {e}')
    exit(1)
" || exit 1
    
    echo ""
    echo -e "${GREEN}✓ API key added successfully!${NC}"
    echo ""
    
    # List current keys (without exposing the actual keys)
    $0 list
}

# List providers in vault
list_providers() {
    echo "Providers configured in vault:"
    echo ""
    
    if [ ! -f "$VAULT_PATH" ]; then
        echo "  No vault found at $VAULT_PATH"
        echo "  Run '$0 init' to create a new vault"
        exit 0
    fi
    
    # Load master key
    if [ -z "$VAULT_MASTER_KEY" ]; then
        if [ -f "$MASTER_KEY_FILE" ]; then
            export VAULT_MASTER_KEY=$(cat "$MASTER_KEY_FILE")
        else
            echo "  Master key not found (set VAULT_MASTER_KEY to view providers)"
            exit 0
        fi
    fi
    
    # List providers using Python
    python3 -c "
import os
from src.core.vault import Vault

vault = Vault.create(
    backend='encrypted',
    vault_path='$VAULT_PATH',
    master_key=os.environ['VAULT_MASTER_KEY']
)

providers = vault.list_providers()
if providers:
    for p in providers:
        print(f'  ✓ {p}')
else:
    print('  No providers configured yet')
    print('  Use add-key command to add providers:')
    print('    $0 add-key openai <api_key>')
" || echo "  Failed to read vault (check master key)"
}

# Show vault status
show_status() {
    echo "MR-Krabs Vault Status"
    echo "=========================================="
    echo ""
    
    echo "Configuration:"
    echo "  Vault path: $VAULT_PATH"
    echo "  Master key file: $MASTER_KEY_FILE"
    echo ""
    
    # Check if vault exists
    if [ -f "$VAULT_PATH" ]; then
        echo -e "  Vault status: ${GREEN}exists${NC}"
        
        # Get file info
        VAULT_SIZE=$(stat -c%s "$VAULT_PATH" 2>/dev/null || stat -f%z "$VAULT_PATH" 2>/dev/null)
        VAULT_PERMS=$(stat -c%a "$VAULT_PATH" 2>/dev/null || stat -f%Lp "$VAULT_PATH" 2>/dev/null)
        
        echo "  File size: $VAULT_SIZE bytes"
        echo "  Permissions: $VAULT_PERMS"
    else
        echo -e "  Vault status: ${RED}not initialized${NC}"
        echo "  Run '$0 init' to create a new vault"
    fi
    
    echo ""
    
    # Check if master key exists
    if [ -f "$MASTER_KEY_FILE" ]; then
        echo -e "  Master key: ${GREEN}found${NC}"
        
        KEY_PERMS=$(stat -c%a "$MASTER_KEY_FILE" 2>/dev/null || stat -f%Lp "$MASTER_KEY_FILE" 2>/dev/null)
        echo "  Key permissions: $KEY_PERMS"
    else
        echo -e "  Master key: ${RED}not found${NC}"
        echo "  Will be generated during init"
    fi
    
    echo ""
    
    # Show environment status
    if [ -n "$VAULT_MASTER_KEY" ]; then
        echo -e "  VAULT_MASTER_KEY: ${GREEN}set in environment${NC}"
    else
        echo "  VAULT_MASTER_KEY: not set (will load from file)"
    fi
    
    echo ""
    
    # List providers
    list_providers
    
    echo ""
    echo "=========================================="
}

# Main command dispatcher
case "${1:-}" in
    init)
        shift
        init_vault "$@"
        ;;
    add-key)
        shift
        add_key "$@"
        ;;
    list)
        list_providers
        ;;
    status)
        show_status
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        # Default: show status if no command provided
        if [ $# -eq 0 ]; then
            show_status
        else
            echo -e "${RED}Unknown command: $1${NC}"
            echo ""
            show_help
            exit 1
        fi
        ;;
esac
